repos:
  - repo: https://github.com/robert-dumitru/conduit
    # Ruff version.
    rev: v0.12.11
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format
